### ISSUE TITLE
Runtime version error

### ISSUE THREAD

**Issue by ghost** [flathub/com.endlessnetwork.fablemaker#7]
@cassidyjames

The Flathub page says, 'over 5 years ago (Built almost 3 years ago)' for [Fablemaker](https://flathub.org/apps/com.endlessnetwork.fablemaker).

However, the source code seems to use version 23.08.

It looks like the app needs to be rebuilt.

**Comment by cassidyjames** [comment]
Thanks for reporting! It looks like there was an issue with the Flathub bot not running on the repo at the last update, and nobody noticed until now. I went ahead and updated it to use 24.08 as long as I was looking at it, and it has been deployed successfully to Flathub.
